# Generated by Django 4.1 on 2022-10-01 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedBusesToDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'AssignedBusesToDriver',
            },
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_number', models.CharField(max_length=30, unique=True)),
                ('seating_capacity', models.IntegerField()),
                ('service_type', models.CharField(max_length=100)),
                ('bus_model', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Bus',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('cnic', models.CharField(max_length=13, unique=True)),
                ('phone', models.CharField(max_length=13, unique=True)),
                ('address', models.CharField(max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Driver',
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.BooleanField()),
                ('phone', models.CharField(max_length=13)),
                ('cnic', models.CharField(max_length=13)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Passenger',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('via', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Route',
            },
        ),
        migrations.CreateModel(
            name='RouteAssignedToBus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.bus')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.route')),
            ],
            options={
                'verbose_name_plural': 'RouteAssignedToBus',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.DateTimeField()),
                ('arrival', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('bus_assg_driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.assignedbusestodriver')),
                ('route_assg_bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.routeassignedtobus')),
            ],
            options={
                'verbose_name_plural': 'Schedule',
            },
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Terminal',
            },
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_no', models.IntegerField()),
                ('status', models.IntegerField()),
                ('type', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.passenger')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.schedule')),
            ],
            options={
                'verbose_name_plural': 'Tickets',
            },
        ),
        migrations.AddField(
            model_name='route',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_terminal', to='home.terminal'),
        ),
        migrations.AddField(
            model_name='route',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_terminal', to='home.terminal'),
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('passenger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.passenger')),
                ('route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.route')),
            ],
            options={
                'verbose_name_plural': 'Refund',
            },
        ),
        migrations.CreateModel(
            name='Fares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fare', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('route_asg_to_bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.routeassignedtobus')),
            ],
            options={
                'verbose_name_plural': 'Fares',
            },
        ),
        migrations.AddField(
            model_name='assignedbusestodriver',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.bus'),
        ),
        migrations.AddField(
            model_name='assignedbusestodriver',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.driver'),
        ),
    ]
