# Generated by Django 4.1 on 2022-10-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_schedule_bus_assg_driver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickets',
            old_name='passenger',
            new_name='bookedby',
        ),
        migrations.AddField(
            model_name='tickets',
            name='gender',
            field=models.BooleanField(default=True),
        ),
    ]
