# Generated by Django 4.1 on 2022-10-05 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_passenger_tickets_bookedby_tickets_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='gender',
            field=models.BooleanField(),
        ),
    ]
