# Generated by Django 4.1 on 2022-10-13 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_schedule_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedbusestodriver',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.driver'),
        ),
    ]
