# Generated by Django 4.1 on 2022-10-23 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_assignedbusestodriver_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routeassignedtobus',
            name='bus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.bus'),
        ),
    ]
