# Generated by Django 4.1 on 2022-10-23 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_routeassignedtobus_bus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund',
            name='route',
        ),
        migrations.AddField(
            model_name='refund',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='refund',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.schedule'),
        ),
    ]
