# Generated by Django 4.1 on 2022-10-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_tickets_voucher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='voucher',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
