# Generated by Django 4.1 on 2022-11-01 01:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0014_alter_tickets_voucher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher', models.CharField(max_length=200, unique=True)),
                ('refreshment', models.IntegerField()),
                ('washing', models.IntegerField()),
                ('parking', models.IntegerField()),
                ('toll', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.schedule')),
                ('terminal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.terminal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Voucher',
            },
        ),
    ]
