# Generated by Django 4.1 on 2022-11-01 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_voucher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voucher',
            old_name='user',
            new_name='issuedby',
        ),
    ]
